#!/usr/bin/env python
"""
len is a recipe language for lazy meta programming
"""
from l.basic.log.logger import get_logger
from l.basic.cfg import get_config
from l.basic.cli.parser import get_parser
from l.basic.cli.app import CliApp


print(__module__)

logger = get_logger()
config = get_config()
parser = get_parser()


CliApp(
    app_logger=logger,
    app_config=config,
    app_parser=parser,
    location=__file__,
).run()
