#!/usr/bin/env python
"""
len is a recipe language for lazy meta programming
"""
from l.cfg.logger import get_config
from l.log.logger import get_logger
from l.cli.parser import get_parser
from l.cli.app import CliApp


logger = get_logger()
config = get_config()
parser = get_parser()


CliApp(
    app_logger=logger,
    app_config=config,
    app_parser=parser,
    location=__file__,
).run()
